/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface DesignerPage {
        "tplName": string;
        "tplPackage"?: string;
    }
    interface DesignerStage {
        "pageHeight": string;
        "pageWidth": string;
    }
    interface DesignerUi {
        "sampleData"?: any;
        "tplName": string;
    }
    interface GraphPaper {
        "height": string;
        "width": string;
    }
    interface HomePage {
        "templates": { ident: string; title: string; description: string; }[];
    }
    interface PrintContentPage {
        "tplName": string;
    }
    interface PrintFooterPage {
        "tplName": string;
    }
    interface PrintHeaderPage {
        "tplName": string;
    }
    interface TemplateUpload {
    }
    interface TplbImageFetch {
        "imgSrc": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDesignerPageElement extends Components.DesignerPage, HTMLStencilElement {
    }
    var HTMLDesignerPageElement: {
        prototype: HTMLDesignerPageElement;
        new (): HTMLDesignerPageElement;
    };
    interface HTMLDesignerStageElement extends Components.DesignerStage, HTMLStencilElement {
    }
    var HTMLDesignerStageElement: {
        prototype: HTMLDesignerStageElement;
        new (): HTMLDesignerStageElement;
    };
    interface HTMLDesignerUiElement extends Components.DesignerUi, HTMLStencilElement {
    }
    var HTMLDesignerUiElement: {
        prototype: HTMLDesignerUiElement;
        new (): HTMLDesignerUiElement;
    };
    interface HTMLGraphPaperElement extends Components.GraphPaper, HTMLStencilElement {
    }
    var HTMLGraphPaperElement: {
        prototype: HTMLGraphPaperElement;
        new (): HTMLGraphPaperElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLPrintContentPageElement extends Components.PrintContentPage, HTMLStencilElement {
    }
    var HTMLPrintContentPageElement: {
        prototype: HTMLPrintContentPageElement;
        new (): HTMLPrintContentPageElement;
    };
    interface HTMLPrintFooterPageElement extends Components.PrintFooterPage, HTMLStencilElement {
    }
    var HTMLPrintFooterPageElement: {
        prototype: HTMLPrintFooterPageElement;
        new (): HTMLPrintFooterPageElement;
    };
    interface HTMLPrintHeaderPageElement extends Components.PrintHeaderPage, HTMLStencilElement {
    }
    var HTMLPrintHeaderPageElement: {
        prototype: HTMLPrintHeaderPageElement;
        new (): HTMLPrintHeaderPageElement;
    };
    interface HTMLTemplateUploadElement extends Components.TemplateUpload, HTMLStencilElement {
    }
    var HTMLTemplateUploadElement: {
        prototype: HTMLTemplateUploadElement;
        new (): HTMLTemplateUploadElement;
    };
    interface HTMLTplbImageFetchElement extends Components.TplbImageFetch, HTMLStencilElement {
    }
    var HTMLTplbImageFetchElement: {
        prototype: HTMLTplbImageFetchElement;
        new (): HTMLTplbImageFetchElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "designer-page": HTMLDesignerPageElement;
        "designer-stage": HTMLDesignerStageElement;
        "designer-ui": HTMLDesignerUiElement;
        "graph-paper": HTMLGraphPaperElement;
        "home-page": HTMLHomePageElement;
        "print-content-page": HTMLPrintContentPageElement;
        "print-footer-page": HTMLPrintFooterPageElement;
        "print-header-page": HTMLPrintHeaderPageElement;
        "template-upload": HTMLTemplateUploadElement;
        "tplb-image-fetch": HTMLTplbImageFetchElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface DesignerPage {
        "tplName"?: string;
        "tplPackage"?: string;
    }
    interface DesignerStage {
        "pageHeight"?: string;
        "pageWidth"?: string;
    }
    interface DesignerUi {
        "onDesigner-reload-preview"?: (event: CustomEvent<void>) => void;
        "sampleData"?: any;
        "tplName"?: string;
    }
    interface GraphPaper {
        "height"?: string;
        "width"?: string;
    }
    interface HomePage {
        "templates"?: { ident: string; title: string; description: string; }[];
    }
    interface PrintContentPage {
        "tplName"?: string;
    }
    interface PrintFooterPage {
        "tplName"?: string;
    }
    interface PrintHeaderPage {
        "tplName"?: string;
    }
    interface TemplateUpload {
    }
    interface TplbImageFetch {
        "imgSrc"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "designer-page": DesignerPage;
        "designer-stage": DesignerStage;
        "designer-ui": DesignerUi;
        "graph-paper": GraphPaper;
        "home-page": HomePage;
        "print-content-page": PrintContentPage;
        "print-footer-page": PrintFooterPage;
        "print-header-page": PrintHeaderPage;
        "template-upload": TemplateUpload;
        "tplb-image-fetch": TplbImageFetch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "designer-page": LocalJSX.DesignerPage & JSXBase.HTMLAttributes<HTMLDesignerPageElement>;
            "designer-stage": LocalJSX.DesignerStage & JSXBase.HTMLAttributes<HTMLDesignerStageElement>;
            "designer-ui": LocalJSX.DesignerUi & JSXBase.HTMLAttributes<HTMLDesignerUiElement>;
            "graph-paper": LocalJSX.GraphPaper & JSXBase.HTMLAttributes<HTMLGraphPaperElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "print-content-page": LocalJSX.PrintContentPage & JSXBase.HTMLAttributes<HTMLPrintContentPageElement>;
            "print-footer-page": LocalJSX.PrintFooterPage & JSXBase.HTMLAttributes<HTMLPrintFooterPageElement>;
            "print-header-page": LocalJSX.PrintHeaderPage & JSXBase.HTMLAttributes<HTMLPrintHeaderPageElement>;
            "template-upload": LocalJSX.TemplateUpload & JSXBase.HTMLAttributes<HTMLTemplateUploadElement>;
            "tplb-image-fetch": LocalJSX.TplbImageFetch & JSXBase.HTMLAttributes<HTMLTplbImageFetchElement>;
        }
    }
}
