image:
  file: .gitpod.Dockerfile

ports:
  - port: 3333
    visibility: public
    name: Templates-Stencil
    onOpen: ignore
  - port: 3334
    visibility: public
    name: Templates-Lit
    onOpen: ignore
  - port: 6000
    visibility: public
    name: Pdf-Service
    onOpen: ignore
  - port: 6001
    visibility: public
    name: Tpl-Service
    onOpen: ignore
  - port: 6004
    visibility: public
    name: Auth-Service
    onOpen: ignore
  - port: 6002
    visibility: public
    name: Designer
    onOpen: ignore
  - port: 6003
    visibility: public
    name: Print
    onOpen: ignore

tasks:
  - name: Free-Console

  - name: Build
    init: |
      bash build-all.sh
      gp sync-done build
  
  - name: Pdf-Service
    before: cd server/pdf-service
    init: |
      gp sync-await build
      npm i
    command: |
      npx playwright install
      npm run install-browser
      npm run dev
  
  - name: Tpl-Service
    before: cd server/tpl-service
    init: |
      gp sync-await build
      npm i
    command: |
      npm run dev
  
  - name: Auth-Service
    before: cd server/auth-service
    init: |
      gp sync-await build
      npm i
    command: |
      npm run dev
    
  - name: Designer
    before: cd web/designer
    init: |
      gp sync-await build
      npm i
    command: npm start
    openMode: split-right

  - name: Print
    before: cd web/print
    init: |
      gp sync-await build
      npm i
    command: npm start
    openMode: split-right

  - name: Templates-Stencil
    before: cd web/templates/templates-stencil
    init: |
      gp sync-await build
      npm i
    command: npm start
    openMode: split-right