/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GraphPaper {
        "height": string;
        "width": string;
    }
}
declare global {
    interface HTMLGraphPaperElement extends Components.GraphPaper, HTMLStencilElement {
    }
    var HTMLGraphPaperElement: {
        prototype: HTMLGraphPaperElement;
        new (): HTMLGraphPaperElement;
    };
    interface HTMLElementTagNameMap {
        "graph-paper": HTMLGraphPaperElement;
    }
}
declare namespace LocalJSX {
    interface GraphPaper {
        "height"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "graph-paper": GraphPaper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "graph-paper": LocalJSX.GraphPaper & JSXBase.HTMLAttributes<HTMLGraphPaperElement>;
        }
    }
}
