/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LeyaPrintGraphPaper {
        "height": string;
        "width": string;
    }
    interface LeyaPrintImageFetch {
        "externalUrl": boolean;
        "imgAlt": string;
        "imgSrc": string;
    }
    interface LeyaPrintMarkdownConverter {
    }
    interface LeyaPrintWatermark {
    }
}
declare global {
    interface HTMLLeyaPrintGraphPaperElement extends Components.LeyaPrintGraphPaper, HTMLStencilElement {
    }
    var HTMLLeyaPrintGraphPaperElement: {
        prototype: HTMLLeyaPrintGraphPaperElement;
        new (): HTMLLeyaPrintGraphPaperElement;
    };
    interface HTMLLeyaPrintImageFetchElement extends Components.LeyaPrintImageFetch, HTMLStencilElement {
    }
    var HTMLLeyaPrintImageFetchElement: {
        prototype: HTMLLeyaPrintImageFetchElement;
        new (): HTMLLeyaPrintImageFetchElement;
    };
    interface HTMLLeyaPrintMarkdownConverterElement extends Components.LeyaPrintMarkdownConverter, HTMLStencilElement {
    }
    var HTMLLeyaPrintMarkdownConverterElement: {
        prototype: HTMLLeyaPrintMarkdownConverterElement;
        new (): HTMLLeyaPrintMarkdownConverterElement;
    };
    interface HTMLLeyaPrintWatermarkElement extends Components.LeyaPrintWatermark, HTMLStencilElement {
    }
    var HTMLLeyaPrintWatermarkElement: {
        prototype: HTMLLeyaPrintWatermarkElement;
        new (): HTMLLeyaPrintWatermarkElement;
    };
    interface HTMLElementTagNameMap {
        "leya-print-graph-paper": HTMLLeyaPrintGraphPaperElement;
        "leya-print-image-fetch": HTMLLeyaPrintImageFetchElement;
        "leya-print-markdown-converter": HTMLLeyaPrintMarkdownConverterElement;
        "leya-print-watermark": HTMLLeyaPrintWatermarkElement;
    }
}
declare namespace LocalJSX {
    interface LeyaPrintGraphPaper {
        "height"?: string;
        "width"?: string;
    }
    interface LeyaPrintImageFetch {
        "externalUrl"?: boolean;
        "imgAlt"?: string;
        "imgSrc"?: string;
    }
    interface LeyaPrintMarkdownConverter {
    }
    interface LeyaPrintWatermark {
    }
    interface IntrinsicElements {
        "leya-print-graph-paper": LeyaPrintGraphPaper;
        "leya-print-image-fetch": LeyaPrintImageFetch;
        "leya-print-markdown-converter": LeyaPrintMarkdownConverter;
        "leya-print-watermark": LeyaPrintWatermark;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "leya-print-graph-paper": LocalJSX.LeyaPrintGraphPaper & JSXBase.HTMLAttributes<HTMLLeyaPrintGraphPaperElement>;
            "leya-print-image-fetch": LocalJSX.LeyaPrintImageFetch & JSXBase.HTMLAttributes<HTMLLeyaPrintImageFetchElement>;
            "leya-print-markdown-converter": LocalJSX.LeyaPrintMarkdownConverter & JSXBase.HTMLAttributes<HTMLLeyaPrintMarkdownConverterElement>;
            "leya-print-watermark": LocalJSX.LeyaPrintWatermark & JSXBase.HTMLAttributes<HTMLLeyaPrintWatermarkElement>;
        }
    }
}
