/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LeyaPrintGraphPaper {
        "height": string;
        "width": string;
    }
    interface LeyaPrintWatermark {
    }
}
declare global {
    interface HTMLLeyaPrintGraphPaperElement extends Components.LeyaPrintGraphPaper, HTMLStencilElement {
    }
    var HTMLLeyaPrintGraphPaperElement: {
        prototype: HTMLLeyaPrintGraphPaperElement;
        new (): HTMLLeyaPrintGraphPaperElement;
    };
    interface HTMLLeyaPrintWatermarkElement extends Components.LeyaPrintWatermark, HTMLStencilElement {
    }
    var HTMLLeyaPrintWatermarkElement: {
        prototype: HTMLLeyaPrintWatermarkElement;
        new (): HTMLLeyaPrintWatermarkElement;
    };
    interface HTMLElementTagNameMap {
        "leya-print-graph-paper": HTMLLeyaPrintGraphPaperElement;
        "leya-print-watermark": HTMLLeyaPrintWatermarkElement;
    }
}
declare namespace LocalJSX {
    interface LeyaPrintGraphPaper {
        "height"?: string;
        "width"?: string;
    }
    interface LeyaPrintWatermark {
    }
    interface IntrinsicElements {
        "leya-print-graph-paper": LeyaPrintGraphPaper;
        "leya-print-watermark": LeyaPrintWatermark;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "leya-print-graph-paper": LocalJSX.LeyaPrintGraphPaper & JSXBase.HTMLAttributes<HTMLLeyaPrintGraphPaperElement>;
            "leya-print-watermark": LocalJSX.LeyaPrintWatermark & JSXBase.HTMLAttributes<HTMLLeyaPrintWatermarkElement>;
        }
    }
}
