# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/playwright:v1.44.0-focal AS auth-service

COPY ../server/auth-service /leya-print/server/auth-service
WORKDIR /leya-print/server/auth-service
RUN npm install