services:
  server-common:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.server-common

  pdf-service:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.pdf-service
    depends_on:
      - server-common

  tpl-service:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.tpl-service
    depends_on:
      - server-common

  auth-service:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.auth-service
    depends_on:
      - server-common

  web-common:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.web-common

  web-designer:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.web-designer
    depends_on:
      - web-common

  web-print:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.web-print
    depends_on:
      - web-common

  sample-data:
    build:
      context: ../../
      dockerfile: ././infrastructure/Dockerfile.sample-data

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    depends_on:
      - pdf-service
      - tpl-service
      - auth-service
      - web-designer
      - web-print
      - sample-data
    ports:
      - "8080:8080"
