# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/playwright:v1.44.0-focal
RUN npx playwright@1.44 install chromium

RUN apt update && \
    apt install -y curl gnupg2 ca-certificates lsb-release ubuntu-keyring && \
    curl https://nginx.org/keys/nginx_signing.key \
      | gpg --dearmor \
      | tee /usr/share/keyrings/nginx-archive-keyring.gpg > /dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" \
      | tee /etc/apt/sources.list.d/nginx.list > /dev/null && \
    echo "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" \
      | tee /etc/apt/preferences.d/99nginx > /dev/null && \
    apt update && \
    apt install -y nginx

COPY ./root /
RUN chmod 777 /leya-print/start-with-nginx.sh

WORKDIR /leya-print/

EXPOSE 8080
STOPSIGNAL SIGQUIT
CMD ["./start-with-nginx.sh"]
